base_dir_cmu: ./data/cmu/
base_dir_human36: ./data/human36/
batch_size: 16
dataset: H36M
dropout: 0
embed_size: 64
forward_expansion: 4
gradient_clip: 5.0
heads: 4
in_features: 1
input_dim: 16
input_num: 20
learning_rate: 0.0001
node_num: 25
num_layers: 3
out_features: 4
output_T_dim: 25
train_epoches: 10
